### ISSUE TITLE
Creacion de excel para pruebas

### ISSUE THREAD

**Issue by espiguinho** [Arquisoft/Loader_e3a#1]
Crear el excel con los datos de los diferentes agentes
"La introducción de los datos se hará a partir de ficheros Excel. Los campos del fichero Excel son
diferentes a los del sistema anterior, los campos son:
 Nombre (en el caso de personas, contendrá nombre y apellidos)
 Localización (coordenadas geográficas del agente). Este valor es opcional para personas y
entidades. Si no hay localización el valor estará en blanco.
 Email: Correo electrónico de contacto. En el caso de sensores u otro tipo de agentes automáticos,
puede ser el correo electrónico de la persona que lo administra.
 Identificador: Identificador del agente. En caso de personas físicas o entidades puede ser el CIF.
Este identificador será único en el sistema y será el nombre de usuario.
 Tipo: Número entero que representa el tipo de agente. "

**Comment by joseluisbugallo** [comment]
Listo
